using System;
using System.Collections.Generic;

namespace Models.Models;

public partial class ContentBlock
{
    public Guid Id { get; set; }

    public DateTime? CreatedOn { get; set; }

    public Guid? CreatedById { get; set; }

    public DateTime? ModifiedOn { get; set; }

    public Guid? ModifiedById { get; set; }

    public int ProcessListeners { get; set; }

    public string Name { get; set; } = null!;

    public string Description { get; set; } = null!;

    public string Config { get; set; } = null!;

    public Guid? ImageId { get; set; }

    public bool IsAutoGeneratedImage { get; set; }

    public virtual ICollection<ContentBlockFile> ContentBlockFiles { get; set; } = new List<ContentBlockFile>();

    public virtual ICollection<ContentBlockInTag> ContentBlockInTags { get; set; } = new List<ContentBlockInTag>();

    public virtual SysImage? Image { get; set; }

    public virtual ICollection<SysContentBlockLcz> SysContentBlockLczs { get; set; } = new List<SysContentBlockLcz>();
}
